version: "3.9"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: server
    container_name: server
    restart: always
    ports:
      - 7000:8080
    volumes:
      - /tmp/server/npm_cache:/root/.npm:z
      - ./server/src:/usr/src/app/src:z
    environment:
      EXAMPLE_ENV: example

  daemon:
    build:
      context: ./daemon
      dockerfile: Dockerfile
    image: daemon
    container_name: daemon
    restart: always

  ganache:
    image: trufflesuite/ganache:latest
    container_name: ganache
    command: --database.dbPath=/data --wallet.accounts 0xf3aff74e76ab06ba866303284853ab6eef61028409b85d918dbd65ddbb6cf879,10000000000000000000000
    restart: always
    ports:
      - 8545:8545
    volumes:
      - ganache_data:/data

volumes:
  ganache_data:
    driver: local
