version: '3.9'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: server
    container_name: server
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /tmp/server/npm_cache:/root/.npm:z
      - ./server/src:/usr/src/app/src:z
    environment:
      EXAMPLE_ENV: example

  mongo:
    image: mongo:7.0.0-rc8
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  mongo-seed:
    build:
      context: ./mongo-seed
      dockerfile: Dockerfile
    image: mongo-seed
    links:
      - mongo

  ganache:
    image: trufflesuite/ganache:latest
    container_name: ganache
    command: --database.dbPath=/data --wallet.accounts 0xf3aff74e76ab06ba866303284853ab6eef61028409b85d918dbd65ddbb6cf879,10000000000000000000000
    restart: always
    ports:
      - 8545:8545
    volumes:
      - ganache_data:/data

volumes:
  mongo_data:
    driver: local
  ganache_data:
    driver: local