version: '3.9'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: server
    container_name: server
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /tmp/server/npm_cache:/root/.npm:z
      - ./server/src:/usr/src/app/src:z

  mongo:
    image: mongo:7.0.0-rc8
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local